# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Dev\TP1-TC-Grupo3\TP1-TC-Grupo3\designer\tf_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tf_window(object):
    def setupUi(self, tf_window):
        tf_window.setObjectName("tf_window")
        tf_window.resize(700, 566)
        self.verticalLayout = QtWidgets.QVBoxLayout(tf_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tf_title = QtWidgets.QLineEdit(tf_window)
        self.tf_title.setText("")
        self.tf_title.setObjectName("tf_title")
        self.verticalLayout.addWidget(self.tf_title)
        self.tf_raw = QtWidgets.QLineEdit(tf_window)
        self.tf_raw.setEnabled(False)
        self.tf_raw.setObjectName("tf_raw")
        self.verticalLayout.addWidget(self.tf_raw)
        self.expr_plot = ExprWidget(tf_window)
        self.expr_plot.setObjectName("expr_plot")
        self.verticalLayout.addWidget(self.expr_plot)
        self.check_btn = QtWidgets.QPushButton(tf_window)
        self.check_btn.setEnabled(True)
        self.check_btn.setObjectName("check_btn")
        self.verticalLayout.addWidget(self.check_btn)
        self.error_label = QtWidgets.QLabel(tf_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_label.sizePolicy().hasHeightForWidth())
        self.error_label.setSizePolicy(sizePolicy)
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setObjectName("error_label")
        self.verticalLayout.addWidget(self.error_label)
        self.OK_btn = QtWidgets.QDialogButtonBox(tf_window)
        self.OK_btn.setEnabled(True)
        self.OK_btn.setOrientation(QtCore.Qt.Horizontal)
        self.OK_btn.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.OK_btn.setObjectName("OK_btn")
        self.verticalLayout.addWidget(self.OK_btn)

        self.retranslateUi(tf_window)
        self.OK_btn.accepted.connect(tf_window.accept) # type: ignore
        self.OK_btn.rejected.connect(tf_window.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(tf_window)

    def retranslateUi(self, tf_window):
        _translate = QtCore.QCoreApplication.translate
        tf_window.setWindowTitle(_translate("tf_window", "Transfer Function"))
        self.tf_title.setPlaceholderText(_translate("tf_window", "Title"))
        self.tf_raw.setPlaceholderText(_translate("tf_window", "Function"))
        self.check_btn.setText(_translate("tf_window", "Check Expression"))
from src.widgets.exprwidget import ExprWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tf_window = QtWidgets.QDialog()
    ui = Ui_tf_window()
    ui.setupUi(tf_window)
    tf_window.show()
    sys.exit(app.exec_())
